### ISSUE TITLE
Error for ByteCode 13

### ISSUE THREAD

**Issue by Miepee** [colinator27/dog-scepter#24]
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at DogScepterLib.Project.Converters.SoundConverter.<>c__DisplayClass2_0.<ConvertData>b__0(GMNamedSerializable asset) in C:\Users\narr\gitrepos\dog-scepter\DogScepterLib\Project\Converters\SoundConverter.cs:line 112
   at DogScepterLib.Project.Converters.AssetConverter`1.EmptyRefsForNamed(IEnumerable`1 dataAssets, List`1 projectAssets, MakeCachedData makeCachedData) in C:\Users\narr\gitrepos\dog-scepter\DogScepterLib\Project\Converters\IConverter.cs:line 29
   at DogScepterLib.Project.Converters.SoundConverter.ConvertData(ProjectFile pf) in C:\Users\narr\gitrepos\dog-scepter\DogScepterLib\Project\Converters\SoundConverter.cs:line 95
   at DogScepterLib.Project.ProjectFile.ConvertFromData() in C:\Users\narr\gitrepos\dog-scepter\DogScepterLib\Project\ProjectFile.cs:line 167
   at DogScepterLib.Project.ProjectFile..ctor(GMData dataHandle, String directoryPath, Warning warningHandler) in C:\Users\narr\gitrepos\dog-scepter\DogScepterLib\Project\ProjectFile.cs:line 159
   at DogScepterCLI.ConsoleExtensions.OpenProject(IConsole console, GMData data, String directory) in C:\Users\narr\gitrepos\dog-scepter\DogScepterCLI\ConsoleExtensions.cs:line 95
ERROR
System.NullReferenceException: Object reference not set to an instance of an object.
  at DogScepterCLI.Commands.DumpCommand.ExecuteAsync(IConsole console) in C:\Users\narr\gitrepos\dog-scepter\DogScepterCLI\Commands\DumpCommand.cs:65
  at CliFx.CliApplication.RunAsync(ApplicationSchema applicationSchema, CommandInput commandInput) in \home\runner\work\CliFx\CliFx\CliFx\CliApplication.cs:147
  at CliFx.CliApplication.RunAsync(IReadOnlyList`1 commandLineArguments, IReadOnlyDictionary`2 environmentVariables) in \home\runner\work\CliFx\CliFx\CliFx\CliApplication.cs:191
```

Games in question that hit this, were AM2R Demo 1.33 and 1.34

**Comment by colinator27** [comment]
Looks like it's something to do with audio groups not existing... Would need to investigate further. Not sure if I have a copy of those versions on hand myself.
